### PR TITLE
Release v1.11.0

### PR DESCRIPTION
**Pull request by felicianotech**

### CODE REVIEW

**Comment by felicianotech** [comment]
Upstream doesn't have the release ready yet.

**Comment by shanesveller** [comment]
It may significantly explode complexity elsewhere, but I am considering proposing my company shift from the "official" `elixir:1.x` Docker images to the ones offered by an organization in our Elixir ecosystem, Hex.pm, who also power our primary dependency repository:

https://github.com/hexpm/bob/blob/master/README.md#docker-images
https://elixirforum.com/t/yet-another-elixir-and-erlang-docker-image/28740

I base this on the lack-of-blessing by the Elixir core team towards the Git repo that backs the current `elixir` image on Docker Hub, as the author is not officially affiliated with the language core team. There are also some indications that the images offered by the Hex.pm team (many of whom are Elixir core team members or alumni) will be the ones to get the official recommendation moving forward. There are also these open issues indicating some concerning lack-of-upkeep:

https://github.com/c0b/docker-elixir/pull/145
https://github.com/c0b/docker-elixir/issues/144
https://github.com/c0b/docker-elixir/issues/122

**Comment by Schultzer** [comment]
@felicianotech what are the status on this PR? 

> Upstream doesn't have the release ready yet.

AFAIK Elixir 1.11 has been released already.

**Comment by shanesveller** [comment]
> AFAIK Elixir 1.11 has been released already.

The Docker image still has not. I cited several issue threads on the repo that backs that Docker image, the first one in my comment above (https://github.com/c0b/docker-elixir/pull/145) is the most directly pertinent. The repo seems to be unmaintained, the 30-day activity view is pretty sparse and the owner is not replying to threads:

https://github.com/c0b/docker-elixir/pulse/monthly

**Comment by felicianotech** [comment]
This is now to releases behind. We're discussing this internally and will decide on a solution soon.

**Comment by felicianotech** [comment]
Going ahead with this updated image in order to test.

**Comment by felicianotech** [comment]
@shanesveller, @Schultzer Would either of you like to give this a go and confirm that it works for you? We moved our image from relying on an upstream .deb package (which caused the delay) to compiling source ourselfs. The `cimg/elixir:1.11.0` image is the first to be published with this new process. I'd like to get confirmation that this is working well before I publish the v1.11.1 image.

**Comment by felicianotech** [comment]
Version 1.11.1 has now been released as well. This is fully resolved.

**Pull request merged**
