### PR TITLE
add support for Erlang 25.0

### PR DESCRIPTION
**Pull request by Ch4s3**

### CODE REVIEW

**Review by JalexChen — APPROVED** [review]

**Comment by JalexChen** [comment]
@felicianotech  - looks good to me and it seems like erlang-solutions has the 25.0 version running. wanna take a look and confirm if we want to respin and include 25.0?

**Comment by jeremyowensboggs** [comment]
Hi, what is the status of this request?  We would like to upgrade our build process to erlang otp 25.

**Comment by felicianotech** [comment]
@JalexChen I would say only the most recent release, yeah.

**Review by felicianotech — APPROVED** [review]

**Comment by Ch4s3** [comment]
Thanks folks!

**Pull request merged**
